### ISSUE TITLE
Monitors, links and supervision - see how to make it work + document it

### ISSUE THREAD

**Issue by vegabook** [Pyrlang/Pyrlang#26]
http://pyrlang.readthedocs.io/en/latest/node.html

There are a lot of juicy hints in this series of docs about how one might run a supervision strategy for a Pyrlang process. But it is not very user friendly for a beginner, especially considering a large proportion of the python population is not very advanced, and also, a lot of "newbies" (like me) are coming into Erlang world via Elixir. May I propose that one of the core contributors to Pyrlang explain to me exactly how one would run a one-for-one supervision strategy from Erlang master to Pyrlang node, and then I will try to write user-friendly documentation? The core idea is that supervision is one of the main things that Erlang world offers and it should therefore be very clear how this benefit is available in Pyrlang. 

The idea is:

* If Erlang node crashes, Pyrlang node must terminate, but must have a callback for cleanup
* if Pyrlang node or process crashes, then Erlang side must reliably be notified. 

This is as simple as it gets, but would allow us to "compete" against other strategies of interop between Elixir/Erlang and Python, such as zeromq and/or grpc which, apart from supervision strategies, can do most of what pyrlang does (I think).

**Comment by kvakvs** [comment]
There is an ability to "monitor" but no ability to "link". A linked process crashing should send crash signals to other ends of its links, and the will either catch the signal or crash. I think this is mainly unimplemented, because there was no use case or user for it immediately so it was never planned properly.
Another question is supervision. There was no intent to implement a supervisor for Python, but having linked a Python `Process` to Erlang process or to Erlang node, there should be ability to handle the other end disappearing or crashing. Again this was never planned, but could be in the future.

**Comment by kvakvs** [comment]
I will change the issue title to monitors, links and supervision, and then we'll see how to get going with what we have. First i'd like to finish transition to asyncio, though.

**Comment by vegabook** [comment]
So just for me to be sure: right now there is no way to react to a Pyrlang python-side node going down, other than for example implementing heartbeats?

**Comment by kvakvs** [comment]
- [ ] Process links
- [ ] Process monitors
- [ ] Refactor remote notebook call context into a process and monitor/link it

**Comment by kvakvs** [comment]
Links and monitors are working now

Supervision can be done with some effort but not planned for now.
